project:
  type: website

website:
  title: "NASA Fire Tracking"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
    logo: "images/nasa.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/zebbecker/quarto-example
    style: "docked"
    search: true
    contents: 
      - text: "Home/About"
        href: "index.qmd"
      - section: "Data Products"
        href: data-summary.qmd
        contents:
          - api.qmd
          - publications.qmd
          - data_sources.qmd
      - section: "Technical Documentation"
        href: docs.qmd
        contents: 
          - system_architecture.qmd
          - contributing.qmd
          - releasing.qmd
          - fireatlas_core.qmd

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "LICENSE"



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto