project:
  type: website

website:

  title: "NASA Wildfire Tracking Lab"
  repo-url: "https://github.com/zebbecker/quarto-example"
  repo-actions: [edit, issue]
  bread-crumbs: true

  navbar:
    background: "#0032A0"

  sidebar:
    logo: docs/images/nasa.png
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/zebbecker/quarto-example
    style: "docked"
    search: true
    contents: 
      - text: "Home/About"
        href: docs/about.qmd
      - section: "Data"
        contents:
          - title: "Data Products"
            file: docs/data.qmd
          - title: "API" 
            file: docs/api.qmd
          - title: "Publications"
            file: docs/publications.qmd
          - title: "Data Sources"
            file: docs/data_sources.qmd
      - section: "Technical Documentation"
        contents: 
          - title: "System Architecture"
            file: docs/system_architecture.qmd
            toc: true
          - title: "Run New Regions"
            file: docs/new_region.qmd
          - title: "Contributing"
            file: docs/contributing.qmd
          - title: "Releasing"
            file: docs/releasing.qmd
          - fireatlas_core.qmd
          - title: "DPS Debugging"
            file: docs/playbook_dps_debug.md


  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "LICENSE"



format:
  html:
    theme: cosmo
    css: docs/styles.css
    toc: true

execute:
  freeze: auto